name: build
permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths: [ "**/*.py", "pyproject.toml", ".github/workflows/**"]
  pull_request:
    branches: [ main ]
    paths: [ "**/*.py", "pyproject.toml", ".github/workflows/**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --all-extras --all-groups

      - name: Run tests
        run: |
          uv run pytest tests --maxfail=1 --disable-warnings --tb=short  -v